# Generated by Django 3.0.8 on 2024-09-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20240905_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mode_of_entry',
            field=models.CharField(blank=True, default='Direct Entry', max_length=20, null=True),
        ),
    ]
