# Generated by Django 3.0.8 on 2024-09-08 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_auto_20240908_1254'),
        ('account', '0006_auto_20240908_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programme',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='programme.Programme'),
        ),
    ]
