# Generated by Django 3.0.8 on 2024-09-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolfee',
            old_name='level',
            new_name='year',
        ),
    ]
