# Generated by Django 3.0.8 on 2024-09-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0002_auto_20240908_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfee',
            name='for_indigene',
            field=models.BooleanField(default=False),
        ),
    ]
