# Generated by Django 3.0.8 on 2024-09-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_auto_20240908_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='programme.Faculty'),
        ),
    ]
