# Generated by Django 3.0.8 on 2024-09-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0006_semester_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(blank=True, choices=[('First', 'First'), ('Second', 'Second')], max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(max_length=50)),
                ('credit', models.IntegerField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('semester', models.CharField(choices=[('First', 'First'), ('Second', 'Second')], max_length=6)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='programme.Programme')),
            ],
        ),
    ]
