# Generated by Django 3.0.8 on 2024-09-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0007_auto_20240908_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.IntegerField(),
        ),
    ]
